//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mytask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_product
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> p_type { get; set; }
        public string cust_name { get; set; }
        public string address { get; set; }
        public Nullable<decimal> M_number { get; set; }
        public Nullable<int> region { get; set; }
        public string s_no { get; set; }
    }
}
